/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Asdf: typeof import('./src/components/editor/Asdf.vue')['default']
    AuxRegisters: typeof import('./src/components/emulator/AuxRegisters.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    DataRegisters: typeof import('./src/components/emulator/DataRegisters.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DownloadButton: typeof import('./src/components/editor/DownloadButton.vue')['default']
    EditAuxTable: typeof import('./src/components/editor/EditAuxTable.vue')['default']
    EditOperationsTable: typeof import('./src/components/editor/EditOperationsTable.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    EditProgramTable: typeof import('./src/components/editor/EditProgramTable.vue')['default']
    Emulator: typeof import('./src/components/Emulator.vue')['default']
    Error: typeof import('./src/components/emulator/Error.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ProgramRegisters: typeof import('./src/components/emulator/ProgramRegisters.vue')['default']
    RegisterTable: typeof import('./src/components/editor/RegisterTable.vue')['default']
    UploadProgramButton: typeof import('./src/components/editor/UploadProgramButton.vue')['default']
  }
}
