/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuxRegisters: typeof import('./src/components/emulator/AuxRegisters.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmPopup: typeof import('primevue/confirmpopup')['default']
    ContextMenu: typeof import('primevue/contextmenu')['default']
    DataRegisters: typeof import('./src/components/emulator/DataRegisters.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DownloadButton: typeof import('./src/components/DownloadButton.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    Emulator: typeof import('./src/components/Emulator.vue')['default']
    Error: typeof import('./src/components/emulator/Error.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    OperationsTable: typeof import('./src/components/editor/OperationsTable.vue')['default']
    ProgramRegisters: typeof import('./src/components/emulator/ProgramRegisters.vue')['default']
    RegisterTable: typeof import('./src/components/RegisterTable.vue')['default']
    ResetButton: typeof import('./src/components/ResetButton.vue')['default']
    SplitButton: typeof import('primevue/splitbutton')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    UploadButton: typeof import('./src/components/UploadButton.vue')['default']
  }
}
